In [1]:
# Date: 3-Oct-2019
# Exploring Numpy

import numpy as np

In [2]:
# Define list
lst=[1,2,3,4,5]

# Convert list to Array
arr=np.array(lst)
arr

array([1, 2, 3, 4, 5])

In [3]:
arr.shape

(5,)

In [4]:
arr.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [5]:
arr.shape

(5,)

In [6]:
# 2-D Array

l1=[1,2,3,4,5]
l2=[6,7,8,9,10]
l3=[11,12,13,14,15]

arr=np.array([l1,l2,l3])


arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [7]:
arr.shape

(3, 5)

In [8]:
arr.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

# Indexing

In [9]:
arr=np.array([1,2,3,4,5])

In [10]:
# 1st position starts with 0 index

arr[3]

4

In [11]:
# 2-D Array

l1=[1,2,3,4,5]
l2=[6,7,8,9,10]
l3=[11,12,13,14,15]

arr=np.array([l1,l2,l3])


arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [12]:
arr[2,0]

11

In [13]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [14]:
arr[1:,2:4]

array([[ 8,  9],
       [13, 14]])

In [15]:
arr[1,1:4]

array([7, 8, 9])